main/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <description>Details of a loan made by the company.</description>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/objects/Loan__c/fields/Date_Loan_Issued__c.field-meta.xml
<CustomField>
    <fullName>Date_Loan_Issued__c</fullName>
    <description>The date the loan was initially issued.</description>
    <inlineHelpText>The date the loan was initially issued.</inlineHelpText>
    <label>Loan Issue Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

main/objects/Loan__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <description>The duration of the loan in months.</description>
    <inlineHelpText>The duration of the loan in months.</inlineHelpText>
    <label>Loan Term (Months)</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/objects/Loan_Charge__c/Loan_Charge__c.object-meta.xml
<CustomObject>
    <description>Charges associated with each loan.</description>
    <label>Loan Charge</label>
    <nameField>
        <displayFormat>LC-{0000000000}</displayFormat>
        <label>Loan Charge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/objects/Loan_Charge__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The monetary value of the charge.</description>
    <inlineHelpText>The monetary value of the charge.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/objects/Loan_Charge__c/fields/Charge_Date__c.field-meta.xml
<CustomField>
    <fullName>Charge_Date__c</fullName>
    <description>The date the charge was applied.</description>
    <inlineHelpText>The date the charge was applied.</inlineHelpText>
    <label>Charge Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

main/objects/Loan_Charge__c/fields/Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type__c</fullName>
    <description>Type of charge being applied to loan.</description>
    <inlineHelpText>Type of charge being applied to loan.</inlineHelpText>
    <label>Charge Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Loan_Charge_Type</valueSetName>
    </valueSet>
</CustomField>

main/objects/Loan_Charge__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <description>The loan to which the charge applies.</description>
    <inlineHelpText>The loan to which the charge applies.</inlineHelpText>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Loan Charges</relationshipLabel>
    <relationshipName>Loan_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/globalValueSets/Loan_Charge_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Release Charge</fullName>
        <default>true</default>
        <label>Release Charge</label>
    </customValue>
    <customValue>
        <fullName>Interest Charge</fullName>
    </customValue>
    <customValue>
        <fullName>Legal Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Admin Fee</fullName>
    </customValue>
    <description>The types of loan charge that can be made.</description>
    <masterLabel>Loan Charge Type</masterLabel>
</GlobalValueSet>

main/classes/LoanChargeTriggerHandler.cls
/**
 * @description
 * @author Mark Brennand
 */
public with sharing class LoanChargeTriggerHandler {

    /**
     * @description
     * Processes the Loan Charge records passed to the trigger.
     *
     * @param triggerType Type of trigger action being performed.
     * @param loanCharges The records that are being persisted.
     * @param oldLoanCharges The previous value of the records being persisted if an update is being performed.
     */
    public static void processRecords(
            final TriggerType triggerType,
            final List<Loan_Charge__c> loanCharges,
            final Map<Id, Loan_Charge__c> oldLoanCharges
    ) {
        final Set<Id> loanIds = new Set<Id>();
        for (Loan_Charge__c loanCharge : loanCharges) {
            loanIds.add(loanCharge.Loan__c);
        }

        final Map<Id, Loan__c> loans = new Map<Id, Loan__c>(getLoans(loanIds));
        final Map<Id, Loan_Charge__c> releaseCharges = new Map<Id, Loan_Charge__c>();

        for (Loan_Charge__c loanCharge : getLoanCharges(loanIds, Helper.RELEASE_CHARGE)) {
            if (!releaseCharges.containsKey(loanCharge.Loan__c)) {
                releaseCharges.put(loanCharge.Loan__c, loanCharge);
            } else {
                // We have more than one Release Charge for the same Loan. So, set the Loan Charge to null in
                // the Map to indicate that any Release Charge records for this Loan are in error.
                releaseCharges.put(loanCharge.Loan__c, null);
            }
        }

        if (validate(triggerType, loanCharges, oldLoanCharges, loans, releaseCharges)) {
            processReleaseCharge(loanCharges, releaseCharges);
        }
    }

    private static Boolean validate(
            final TriggerType type,
            final List<Loan_Charge__c> loanCharges,
            final Map<Id, Loan_Charge__c> oldLoanCharges,
            final Map<Id, Loan__c> loans,
            final Map<Id, Loan_Charge__c> releaseCharges
    ) {
        Boolean valid = true;

        switch on type {
            when CREATED {
                for (Loan_Charge__c loanCharge : loanCharges) {
                    valid &= validateDate(loanCharge, loans.get(loanCharge.Loan__c));

                    if ((loanCharge.Charge_Type__c == Helper.RELEASE_CHARGE)
                            && (releaseCharges.containsKey(loanCharge.Loan__c)
                            && loanCharge.Id != releaseCharges.get(loanCharge.Loan__c)?.Id))
                    {
                        loanCharge.Charge_Type__c.addError(Label.Only_One_Release_Charge_Allowed);
                        valid = false;
                    }
                }
            }

            when UPDATED {
                for (Loan_Charge__c loanCharge : loanCharges) {
                    valid &= validateDate(loanCharge, loans.get(loanCharge.Loan__c));

                    final Loan_Charge__c oldLoanCharge = oldLoanCharges.get(loanCharge.Id);
                    if (oldLoanCharge.Charge_Type__c != loanCharge.Charge_Type__c) {
                        loanCharge.Charge_Type__c.addError(Label.Charge_Type_Cannot_Be_Changed);
                        valid = false;
                    }
                }
            }

            when DELETED {
                for (Loan_Charge__c loanCharge : loanCharges) {
                    if (loanCharge.Charge_Type__c == Helper.RELEASE_CHARGE) {
                        loanCharge.addError(Label.Release_Charge_Cannot_Be_Deleted);
                        valid = false;
                    }
                }
            }
        }

        return valid;
    }

    private static void processReleaseCharge(
            final List<Loan_Charge__c> loanCharges,
            final Map<Id, Loan_Charge__c> releaseCharges
    ) {
        final Map<Id, Date> latestDates = new Map<Id, Date>();
        for (Loan_Charge__c loanCharge : loanCharges) {
            if (loanCharge.Charge_Type__c != Helper.RELEASE_CHARGE) {
                if (latestDates.containsKey(loanCharge.Loan__c)) {
                    if (loanCharge.Charge_Date__c > latestDates.get(loanCharge.Loan__c)) {
                        latestDates.put(loanCharge.Loan__c, loanCharge.Charge_Date__c);
                    }

                } else {
                    latestDates.put(loanCharge.Loan__c, loanCharge.Charge_Date__c);
                }
            }
        }

        final List<Loan_Charge__c> releaseChargesToUpdate = new List<Loan_Charge__c>();
        for (Id loanId : latestDates.keySet()) {
            final Loan_Charge__c releaseCharge = releaseCharges.get(loanId);
            final Date latestDate = latestDates.get(loanId);

            if (latestDate >= releaseCharge.Charge_Date__c) {
                // The records have come from SF, so are immutable. Hence, clone the record to persist.
                Loan_Charge__c cloned = releaseCharge.clone(true);
                cloned.Charge_Date__c = latestDate.addMonths(1);
                releaseChargesToUpdate.add(cloned);
            }
        }

        Database.upsert(releaseChargesToUpdate, AccessLevel.USER_MODE);
    }

    private static Boolean validateDate(final Loan_Charge__c loanCharge, final Loan__c loan) {
        if (loanCharge.Charge_Type__c == Helper.INTEREST_CHARGE && loanCharge.Charge_Date__c < loan.Date_Loan_Issued__c) {
            loanCharge.Charge_Date__c.addError(Label.Invalid_Interest_Charge_Date);
            return false;
        }

        return true;
    }

    private static List<Loan_Charge__c> getLoanCharges(final Set<Id> loanIds, final String chargeType) {
        return [
                SELECT Id, Loan__c, Amount__c, Charge_Type__c, Charge_Date__c
                FROM Loan_Charge__c
                WHERE Loan__c IN :loanIds
                AND Charge_Type__c = :chargeType
                WITH USER_MODE
        ];
    }

    private static List<Loan__c> getLoans(final Set<Id> loanIds) {
        return [
                SELECT Id, Date_Loan_Issued__c, Term__c
                FROM Loan__c
                WHERE Id IN :loanIds
        ];
    }
}