main/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <description>Details of a loan made by the company.</description>
    <label>Loan</label>
    <nameField>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/objects/Loan__c/fields/Date_Loan_Issued__c.field-meta.xml
<CustomField>
    <fullName>Date_Loan_Issued__c</fullName>
    <description>The date the loan was initially issued.</description>
    <inlineHelpText>The date the loan was initially issued.</inlineHelpText>
    <label>Loan Issue Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

main/objects/Loan__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <description>The duration of the loan in months.</description>
    <inlineHelpText>The duration of the loan in months.</inlineHelpText>
    <label>Loan Term (Months)</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/objects/Loan_Charge__c/Loan_Charge__c.object-meta.xml
<CustomObject>
    <description>Charges associated with each loan.</description>
    <label>Loan Charge</label>
    <nameField>
        <displayFormat>LC-{0000000000}</displayFormat>
        <label>Loan Charge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/objects/Loan_Charge__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>The monetary value of the charge.</description>
    <inlineHelpText>The monetary value of the charge.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

main/objects/Loan_Charge__c/fields/Charge_Date__c.field-meta.xml
<CustomField>
    <fullName>Charge_Date__c</fullName>
    <description>The date the charge was applied.</description>
    <inlineHelpText>The date the charge was applied.</inlineHelpText>
    <label>Charge Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

main/objects/Loan_Charge__c/fields/Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type__c</fullName>
    <description>Type of charge being applied to loan.</description>
    <inlineHelpText>Type of charge being applied to loan.</inlineHelpText>
    <label>Charge Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Loan_Charge_Type</valueSetName>
    </valueSet>
</CustomField>

main/objects/Loan_Charge__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <description>The loan to which the charge applies.</description>
    <inlineHelpText>The loan to which the charge applies.</inlineHelpText>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Loan Charges</relationshipLabel>
    <relationshipName>Loan_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/globalValueSets/Loan_Charge_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Release Charge</fullName>
        <default>true</default>
        <label>Release Charge</label>
    </customValue>
    <customValue>
        <fullName>Interest Charge</fullName>
    </customValue>
    <customValue>
        <fullName>Legal Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Admin Fee</fullName>
    </customValue>
    <description>The types of loan charge that can be made.</description>
    <masterLabel>Loan Charge Type</masterLabel>
</GlobalValueSet>

main/classes/LoanTriggerHandler.cls
/**
 * @description
 * Class implementing logic required for Loan trigger.
 *
 * Bulkification is used wherever possible.
 *
 * @author Mark Brennand
 */
public with sharing class LoanTriggerHandler {

    /**
     * @description
     * Processes the Loan records passed to the trigger.
     *
     * @param type Type of trigger action being performed.
     * @param loans The records that are being persisted.
     * @param oldLoans The previous value of the records being persisted if an update is being performed.
     */
    public static void processRecords(
            final TriggerType type,
            final List<Loan__c> loans,
            final Map<Id, Loan__c> oldLoans
    ) {
        switch on type {
            when CREATED {
                addReleaseCharge(loans);
            }
            when UPDATED {
                adjustReleaseCharge(loans, oldLoans);
            }
        }
    }

    private static void addReleaseCharge(final List<Loan__c> loans) {
        final List<Loan_Charge__c> releaseCharges = new List<Loan_Charge__c>();
        for (Loan__c loan : loans) {
            releaseCharges.add(
                    new Loan_Charge__c(
                            Loan__c = loan.Id,
                            Charge_Type__c = Helper.RELEASE_CHARGE,
                            Amount__c = Helper.RELEASE_CHARGE_FEE,
                            Charge_Date__c = loan.Date_Loan_Issued__c.addMonths((Integer) loan.Term__c)
                    )
            );
        }

        Database.insert(releaseCharges, AccessLevel.USER_MODE);
    }

    private static void adjustReleaseCharge(final List<Loan__c> loans, Map<Id, Loan__c> oldLoans) {
        final Set<Id> changedTermIds = new Set<Id>();
        final Map<Id, Date> endDates = new Map<Id, Date>();

        for (Loan__c loan : loans) {
            if (loan.Term__c != oldLoans.get(loan.Id)?.Term__c) {
                changedTermIds.add(loan.Id);
                endDates.put(loan.Id, loan.Date_Loan_Issued__c.addMonths((Integer) loan.Term__c));
            }
        }

        if (changedTermIds.isEmpty()) {
            return;
        }

        final List<Loan_Charge__c> releaseCharges = [
                SELECT Id, Loan__c, Charge_Date__c, Charge_Type__c
                FROM Loan_Charge__c
                WHERE Loan__c IN :changedTermIds AND Charge_Type__c = :Helper.RELEASE_CHARGE
        ];

        final Map<Id, Loan_Charge__c> releaseChargeLookup = new Map<Id, Loan_Charge__c>();
        for (Loan_Charge__c releaseCharge : releaseCharges) {
            releaseChargeLookup.put(releaseCharge.Loan__c, releaseCharge);
        }

        for (Id changedTermId : changedTermIds) {
            releaseChargeLookup.get(changedTermId).Charge_Date__c = endDates.get(changedTermId);
        }

        // This is something odd about SF. Setting the AccessLevel to USER_MODE causes an inaccessible field exception
        // despite a user with the Loan Manager permission set having full access to the Loan_Charge__c object.
        //
        // I think it's ok to use SYSTEM_MODE here as we wouldn't be reaching this point in the code if the user
        // didn't have write access to the Loan_Charge__c object.
        Database.update(releaseCharges, AccessLevel.SYSTEM_MODE);

        final List<Loan_Charge__c> adminCharges = new List<Loan_Charge__c>();
        for (Id changedTermId : changedTermIds) {
            adminCharges.add(
                    new Loan_Charge__c(
                            Loan__c = changedTermId,
                            Charge_Date__c = Helper.NOW.date(),
                            Charge_Type__c = Helper.ADMIN_FEE,
                            Amount__c = Helper.CHANGE_TERM_FEE
                    )
            );
        }

        Database.insert(adminCharges, AccessLevel.USER_MODE);
    }
}